Generate and store csv reports
ursacomputing/crossbow pull request #20
Opened 2022-05-24 14:57 UTC by raulcd

This change will add a couple of new steps to the Nightly reports.
It will generate a CSV file with the report and it will automatically commit it and store it to the csv_reports folder.

An example of execution of this new workflow can be seen on my fork.
This is an example of the execution, bear in mind I had to do some minor modifications to make it work on my fork:
https://github.com/raulcd/crossbow/runs/6575792648?check_suite_focus=true
And the generated commit can be seen here:
https://github.com/raulcd/crossbow/commit/a6eed0d1c2d7f04a9c14a38606bbbac949e5cf41

2022-05-24 15:15 UTC, assignUser requested changes
Nice work! Just one comment :)

2022-05-24 15:15 UTC, assignUser commented on .github/workflows/report.yml
> +        uses: stefanzweifel/git-auto-commit-action@v4
I would prefer not to use third-party (not actions/* or r-lib/actions ) actions for something that could be done relatively easily via bash/gh API. We should pin a hash instead of a version tag at least.

2022-05-24 15:23 UTC, raulcd commented on .github/workflows/report.yml
> +        uses: stefanzweifel/git-auto-commit-action@v4
yeah, I agree but I saw that even GitHub was recommending it on their blog posts:
https://github.blog/2020-09-17-github-action-hero-stefan-zweifel-and-git-auto-commit/

I will give it a try to do it manually or at least use a tag! Thanks!

2022-05-25 09:00 UTC, raulcd commented on .github/workflows/report.yml
> +        uses: stefanzweifel/git-auto-commit-action@v4
I have updated the job to do it manually now

2022-05-25 09:28 UTC, jorisvandenbossche commented on .github/workflows/report.yml
> +            --author="${{ github.actor }} <${{ github.actor }}@users.noreply.github.com>"
Who will be the actor here if this is run from ursacomputing/crossbow?

2022-05-25 11:16 UTC, raulcd commented on .github/workflows/report.yml
> +            --author="${{ github.actor }} <${{ github.actor }}@users.noreply.github.com>"
It is supposed to be:
```
The username of the user that initiated the workflow run.
```
In that case if we take a look at the scheduled actions it seems to pick the last committer as the user that initiated the workflow.

2022-05-25 12:15 UTC, raulcd commented on .github/workflows/report.yml
> +            --author="${{ github.actor }} <${{ github.actor }}@users.noreply.github.com>"
Ok, that works. I have tested on my fork with this commit: https://github.com/raulcd/crossbow/commit/68c1215c125ef6c685fa76a48a844c82f9e98dac
I've pushed the suggested change. Thanks @jorisvandenbossche

2022-05-25 12:17 UTC, jorisvandenbossche reviewed
Thanks! Let's give this a try

2022-05-25 12:17 UTC, merged